### ISSUE TITLE
PyScreenshot error while running test.py

### ISSUE THREAD

**Issue by fsilly** [alexeykuzmin/google-maps-screenshot#1]
Hello, I am trying to take a very large screenshot of google maps street, this is the best project i found on the internet to fill my needs so far. Im running it on windows, i started test.py when this error came :

```
DevTools listening on ws://127.0.0.1:54246/devtools/browser/c265a81f-6d32-4937-b969-3e286e6f9e76
[10896:31096:0405/114233.583:ERROR:device_event_log_impl.cc(214)] [11:42:33.583] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
[10896:31096:0405/114233.585:ERROR:device_event_log_impl.cc(214)] [11:42:33.585] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "C:\Users\me\Downloads\google-maps-screenshot-taker-main\google-maps-screenshot-taker-main\test.py", line 35, in <module>
    take_screenshot(
  File "C:\Users\me\Downloads\google-maps-screenshot-taker-main\google-maps-screenshot-taker-main\test.py", line 17, in take_screenshot
    create_map(
  File "C:\Users\me\Downloads\google-maps-screenshot-taker-main\google-maps-screenshot-taker-main\main.py", line 190, in create_map
    image = screenshot(screen_width, screen_height, offset_left, offset_top, offset_right, offset_bottom)
  File "C:\Users\me\Downloads\google-maps-screenshot-taker-main\google-maps-screenshot-taker-main\main.py", line 60, in screenshot
    image = pyscreenshot.grab(bbox=(x1, y1, x2, y2))
  File "E:\Programmes\AdvancedDevTools\AdvancedKernels\Python\Python3.10\lib\site-packages\pyscreenshot\__init__.py", line 30, in grab
    return backend_grab(backend, bbox, childprocess)
  File "E:\Programmes\AdvancedDevTools\AdvancedKernels\Python\Python3.10\lib\site-packages\pyscreenshot\loader.py", line 158, in backend_grab
    return auto(bbox, childprocess)
  File "E:\Programmes\AdvancedDevTools\AdvancedKernels\Python\Python3.10\lib\site-packages\pyscreenshot\loader.py", line 138, in auto
    raise FailedBackendError(msg)
pyscreenshot.err.FailedBackendError: All backends failed!
```

**Comment by fsilly** [comment]
A little bit of your time to help would be very much apreciated.

My best regards,
Yan.
